services:
    _defaults:
        public: true
        autowire: true
    #    attribute.example:
    #        class: AttributeBundle\Example
    #        arguments: [@service_id, "plain_value", %parameter%]
    attribute.attribute_value:
        class: gbenitez\Bundle\AttributeBundle\Form\Type\AttributeValueType
        arguments:
            - "@=service('doctrine.orm.entity_manager').getRepository('GbenitezAttributeBundle:Attribute')"
            - "@doctrine.orm.entity_manager"
            - "@translator"
        tags:
            - { name: form.type, alias: attribute_value }

    attribute.attributes:
        class: gbenitez\Bundle\AttributeBundle\Form\Type\AttributesType
        tags:
            - { name: form.type, alias: attributes }

    attribute.repository:
        class: gbenitez\Bundle\AttributeBundle\Entity\Repository\AttributeRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [AttributeBundle:Attribute]

    attribute.yaml:
        class: gbenitez\Bundle\AttributeBundle\Form\Type\YamlType
        tags:
            - { name: form.type }

    attribute.manager:
        class: gbenitez\Bundle\AttributeBundle\Model\AttributeManager
        arguments:
            - "@doctrine.orm.entity_manager"

    attribute.form.type.target_entity:
        class: gbenitez\Bundle\AttributeBundle\Form\Type\Admin\TargetEntityType
        arguments: [""]
        tags:
            - { name: "form.type" }

    gbenitez\Bundle\AttributeBundle\Form\Region\AttributeRegionFilter: ~
        #class: gbenitez\Bundle\AttributeBundle\Form\Region\AttributeRegionFilter
        #autowire: true

    gbenitez\Bundle\AttributeBundle\Model\Region\AttributeRegionResolver: ~
        #class: gbenitez\Bundle\AttributeBundle\Model\Region\AttributeRegionResolver
        #autowire: true


    gbenitez\Bundle\AttributeBundle\Util\AttributeValuePrinter: ~
        #class: gbenitez\Bundle\AttributeBundle\Util\AttributeValuePrinter
        #autowire: true
        #arguments: ['@twig', 'd-m-Y']


    #gbenitez\Bundle\AttributeBundle\Entity\AbstractAttributeValue: ~

    #gbenitez\Bundle\AttributeBundle\Entity\AttributeValueInterface: '@gbenitez\Bundle\AttributeBundle\Entity\AbstractAttributeValue'
    #App\Entity\TargetEntity: ~

    #gbenitez\Bundle\AttributeBundle\Entity\AttributeValueInterface: '@App\Entity\TargetEntity'

    attribute.twig.extension.attribute:
        class: gbenitez\Bundle\AttributeBundle\Twig\Extension\AttributeExtension
        autowire: true
        tags:
            - { name: "twig.extension" }

    attribute.form.type.value_template:
        class: gbenitez\Bundle\AttributeBundle\Form\Type\Admin\ValueTemplateType
        arguments: ["@twig"]
        tags:
            - { name: 'form.type' }

    attribute.extractor.attribute_value:
        class: gbenitez\Bundle\AttributeBundle\Util\AttributeValueArrayExtractor
        autowire: true
        public: false
