services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    Gbenitez\AttributeBundle\Controller\:
        resource: "../src/Controller/"
        tags: ["controller.service_arguments"]

    # Repositories
    Gbenitez\AttributeBundle\Entity\Repository\AttributeRepository:
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - 'Gbenitez\AttributeBundle\Entity\Attribute'

    # Form Types
    Gbenitez\AttributeBundle\Form\Type\:
        resource: "../src/Form/Type/"
        tags: ["form.type"]

    # Models and Services (some disabled due to missing dependencies)
    Gbenitez\AttributeBundle\Model\AttributeManager:
        arguments:
            - "@doctrine.orm.entity_manager"

    # Twig Extensions (disabled for now due to missing dependencies)
    # Gbenitez\AttributeBundle\Twig\Extension\:
    #     resource: "../src/Twig/Extension/"

    # Utilities
    Gbenitez\AttributeBundle\Util\:
        resource: "../src/Util/"

    # Specific service configurations
    Gbenitez\AttributeBundle\Form\Type\Admin\TargetEntityType:
        arguments:
            $targetEntityNames: []
