parameters:
    benitez_attribute.controller.class: Gbenitez\Bundle\AttributeBundle\Controller\AttributeController
    benitez_attribute.attribute_repository.class: Gbenitez\Bundle\AttributeBundle\Entity\Repository\AttributeRepository
    benitez_attribute.attribute_entity.class: Gbenitez\Bundle\AttributeBundle\Entity\Attribute

services:
    Gbenitez\Bundle\AttributeBundle\Controller\AttributeController:
        public: true
        alias: 'benitez_attribute.controller'

    benitez_attribute.controller:
        class: '%benitez_attribute.controller.class%'
        public: true
        arguments:
          - '@attribute.repository'
        autowire: true

    Gbenitez\Bundle\AttributeBundle\Entity\Repository\AttributeRepository:
        class: '%benitez_attribute.attribute_repository.class%'
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:
            - '@attribute.entity'
        alias: 'attribute.repository'
        public: true

    Gbenitez\Bundle\AttributeBundle\Entity\Attribute:
        class: '%benitez_attribute.attribute_entity.class%'
        public: true
        alias: 'attribute.entity'

    attribute.attribute_value:
        class: Gbenitez\Bundle\AttributeBundle\Form\Type\AttributeValueType
        public: true
        arguments:
            - "@=service('doctrine.orm.entity_manager').getRepository('GbenitezAttributeBundle:Attribute')"
            - "@doctrine.orm.entity_manager"
            - "@translator"
        tags:
            - { name: form.type, alias: attribute_value }

    attribute.attributes:
        class: Gbenitez\Bundle\AttributeBundle\Form\Type\AttributesType
        public: true
        tags:
            - { name: form.type, alias: attributes }

    attribute.yaml:
        class: Gbenitez\Bundle\AttributeBundle\Form\Type\YamlType
        public: true
        tags:
            - { name: form.type }

    attribute.manager:
        class: Gbenitez\Bundle\AttributeBundle\Model\AttributeManager
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    attribute.form.type.target_entity:
        class: Gbenitez\Bundle\AttributeBundle\Form\Type\Admin\TargetEntityType
        public: true
        arguments: [""]
        tags:
            - { name: "form.type" }

    Gbenitez\Bundle\AttributeBundle\Form\Region\AttributeRegionFilter: ~

    Gbenitez\Bundle\AttributeBundle\Model\Region\AttributeRegionResolver: ~

    Gbenitez\Bundle\AttributeBundle\Util\AttributeValuePrinter: ~

    attribute.twig.extension.attribute:
        class: Gbenitez\Bundle\AttributeBundle\Twig\Extension\AttributeExtension
        public: true
        tags:
            - { name: "twig.extension" }

    attribute.form.type.value_template:
        class: Gbenitez\Bundle\AttributeBundle\Form\Type\Admin\ValueTemplateType
        public: true
        arguments: ["@twig"]
        tags:
            - { name: 'form.type' }

    attribute.extractor.attribute_value:
        class: Gbenitez\Bundle\AttributeBundle\Util\AttributeValueArrayExtractor
        public: true
