parameters:
    benitez_attribute.controller.class: Gbenitez\AttributeBundle\Controller\AttributeController
    benitez_attribute.attribute_repository.class: Gbenitez\AttributeBundle\Entity\Repository\AttributeRepository
    benitez_attribute.attribute_entity.class: Gbenitez\AttributeBundle\Entity\Attribute

services:
    Gbenitez\AttributeBundle\Entity\Attribute:
        class: '%benitez_attribute.attribute_entity.class%'

    Gbenitez\AttributeBundle\Entity\AttributeRepository:
        class: '%benitez_attribute.attribute_repository.class%'
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:
            - 'Gbenitez\AttributeBundle\Entity\Attribute'

    Gbenitez\AttributeBundle\Controller\AttributeController:
        class: '%benitez_attribute.controller.class%'
        arguments:
          - Gbenitez\AttributeBundle\Entity\AttributeRepository

    attribute.attribute_value:
        class: Gbenitez\AttributeBundle\Form\Type\AttributeValueType
        public: true
        arguments:
            - "@=service('doctrine.orm.entity_manager').getRepository('GbenitezAttributeBundle:Attribute')"
            - "@doctrine.orm.entity_manager"
            - "@translator"
        tags:
            - { name: form.type, alias: attribute_value }

    attribute.attributes:
        class: Gbenitez\AttributeBundle\Form\Type\AttributesType
        public: true
        tags:
            - { name: form.type, alias: attributes }

    attribute.yaml:
        class: Gbenitez\AttributeBundle\Form\Type\YamlType
        public: true
        tags:
            - { name: form.type }

    attribute.manager:
        class: Gbenitez\AttributeBundle\Model\AttributeManager
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    attribute.form.type.target_entity:
        class: Gbenitez\AttributeBundle\Form\Type\Admin\TargetEntityType
        public: true
        arguments: [""]
        tags:
            - { name: "form.type" }

    #Gbenitez\AttributeBundle\Form\Region\AttributeRegionFilter: ~

    #Gbenitez\AttributeBundle\Model\Region\AttributeRegionResolver: ~

    #Gbenitez\AttributeBundle\Util\AttributeValuePrinter: ~

    #attribute.twig.extension.attribute:
        #class: Gbenitez\AttributeBundle\Twig\Extension\AttributeExtension
        #public: true
        #autowire: true
        #autoconfigure: true
        #tags:
            #- { name: "twig.extension" }

    #attribute.form.type.value_template:
        #class: Gbenitez\AttributeBundle\Form\Type\Admin\ValueTemplateType
        #public: true
        #arguments: ["@twig"]
        #tags:
            #- { name: 'form.type' }

    #attribute.extractor.attribute_value:
        #class: Gbenitez\AttributeBundle\Util\AttributeValueArrayExtractor
        #public: true
